
services:

  pgsqlapi:
    container_name: pgsqlapi
    build:
      context: ./pgsqlapi
      dockerfile: dockerfile.pgsqlapi
    image: pgsqlapi:latest
    ports:
      - '5438:5432'
    networks:
      - indices
    restart: always  
    volumes:
      - ./pgsqlapi/db:/var/lib/postgresql/data
      - ./pgsqlapi/backup:/db/backup      
    env_file:
      - ./env/pgsqlapi.env

   
  api:
    container_name: api-indice
    build:
      context: ./api
      dockerfile: ./dockerfile.api
    image: api-indice:latest        
    ports:
      - '8004:8004'
    networks:
      - indices
    restart: on-failure
    volumes:
      - ./api:/api          


networks:
  indices:
    external: true
