version: '3.7'
services:
  pgsql:
    container_name: db-api
    build:
      context: ./postgres
      dockerfile: dockerfile.postgres
    ports:
      - '5435:5432'
    restart: always  
    volumes:
      - ./postgres/db:/var/lib/postgresql/data      
    env_file:
      - ./env/postgres.env
  pgadmin:
    container_name: db-pgadmin
    build:
      context: ./pgadmin
      dockerfile: dockerfile.pgadmin
    ports:
      - "16543:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./env/pgadmin.env    
    depends_on:
      - pgsql
volumes:
  pgadmin-data:
    