FROM postgres:15.3

WORKDIR /db

# Cria a pasta de backup dentro do container
RUN mkdir -p /db/backup && chown -R postgres:postgres /db


#RUN mkdir backup

#COPY indexadores_backup_19.5.2023 .   

#RUN pg_restore -U postgres -d indexadores -1 /db/indexadores_backup_19.5.2023




